name: Docker Buld and Run tests

on:
  pull_request:
    # run on pull request against master
    branches: [master]
  
  push:
    # run on push against master
    branches: [master]
    paths: 
      # if release.json is changed
      - 'release.json'
      # if any of the dockerfile changed
      - '**Dockerfile'

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          content=$(jq -r 'tostring' release.json)
          echo "::set-output name=matrix::$content"
          echo ${{ steps.set-matrix.outputs.matrix }}

  tests:
    # needs the job matrix
    needs: generate_matrix
    runs-on: ubuntu-latest
    strategy:
      # create strategy to run jobs based on the matrix
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}

    steps:
      # checksout the repo to vm
      - uses: actions/checkout@v2
      - name: Build and run test
        run: |
          export BINARY=${{ matrix.binary_version }}
          export PLATFORM=${{ matrix.platform }}
          docker-compose --file ./tests/docker-compose.test.yml build
          docker-compose --file ./tests/docker-compose.test.yml run sut
  
  publish:
    if: github.event_name == 'push'
    needs: [generate_matrix, tests]
    runs-on: ubuntu-latest
    strategy:
      # create strategy to run jobs based on the matrix
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}
    
    steps:
      - uses: actions/checkout@v2
      - name: Publish to registry
        uses: docker/build-push-action@v1.1.0
        with:
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./${{ matrix.binary_version }}/${{ matrix.platform }}/Dockerfile
          tags: "${{ matrix.binary_version }}-${{ matrix.platform }}"

      - name: Update latest
        if: ${{ matrix.latest }}
        uses: docker/build-push-action@v1.1.0
        with:
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./${{ matrix.binary_version }}/${{ matrix.platform }}/Dockerfile
          tags: "latest"
